server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://srxagkdcpyxmqt:6196fa8374975ce62c11c3187bd8ed4e064834f42c418b5452335a1e69b60ad9@ec2-3-234-22-132.compute-1.amazonaws.com:5432/d72arfkh5k6pec
    username: srxagkdcpyxmqt
    password: 6196fa8374975ce62c11c3187bd8ed4e064834f42c418b5452335a1e69b60ad9
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander / Backend